export const enum DOMTypes {
  title = 'title',
  arcordeon = 'arcordeon',
  header = 'header',
  buttonBar = 'buttonBar',
  expansionPanel = 'expansionPanel',
  root = 'root',
  sidenav = 'sidenav',
  searchField = 'searchField',
  sidenavItem = 'sidenavItem',
  None = 0,
  main = 'main',
  body = 'body',
  overlay = 'overlay',
  dialog = 'dialog',
  popup = 'popup',
  footer = 'footer',
  groupSelector = 'groupSelector',
  groupSidenav = 'groupSidenav',
  userSidenav = 'userSidenav',
}
