export const enum DOMTypes {
  body = 'body',
  buttonBar = 'buttonBar',
  content = 'content',
  dialog = 'dialog',
  expansionPanel = 'expansionPanel',
  footer = 'footer',
  groupSelector = 'groupSelector',
  groupSidenav = 'groupSidenav',
  header = 'header',
  main = 'main',
  None = 0,
  overlay = 'overlay',
  popup = 'popup',
  userSidenav = 'userSidenav',
  root = 'root',
  searchField = 'searchField',
  sidenav = 'sidenav',
  sidenavItem = 'sidenavItem',
  title = 'title',
  textNode = 'textNode',
  formularNode = 'formular',
  contentTypePopup = 'contentTypePopup', 
  formularTypePopup = 'formularTypePopup'  
}
