// <auto-generated />
using BuildLogger_DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuildLogger.Migrations
{
    [DbContext(typeof(BuildLoggerContext))]
    [Migration("20200428153029_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BuildLogger_DB_Context.BuildLogRef", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("buildStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("errorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("projectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("serverId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("BuildLog");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Error", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Nav", b =>
                {
                    b.Property<string>("apiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NavapiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("bodyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("apiId");

                    b.HasIndex("NavapiId");

                    b.ToTable("Nav");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.NavNav", b =>
                {
                    b.Property<string>("child_API_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("parent_API_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("childapiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("parentapiId")
                        .HasColumnType("TEXT");

                    b.HasKey("child_API_Id", "parent_API_Id");

                    b.HasIndex("childapiId");

                    b.HasIndex("parentapiId");

                    b.ToTable("NavNav");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Nav", b =>
                {
                    b.HasOne("BuildLogger_DB_Context.Nav", null)
                        .WithMany("navData")
                        .HasForeignKey("NavapiId");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.NavNav", b =>
                {
                    b.HasOne("BuildLogger_DB_Context.Nav", "child")
                        .WithMany()
                        .HasForeignKey("childapiId");

                    b.HasOne("BuildLogger_DB_Context.Nav", "parent")
                        .WithMany()
                        .HasForeignKey("parentapiId");
                });
#pragma warning restore 612, 618
        }
    }
}
