// <auto-generated />
using BuildLogger_DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuildLogger.Migrations
{
    [DbContext(typeof(BuildLoggerContext))]
    partial class BuildLoggerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BuildLogger_DB_Context.BuildLogRef", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("buildStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("errorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("projectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("serverId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("BuildLog");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Error", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Nav", b =>
                {
                    b.Property<string>("APIid")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NavAPIid")
                        .HasColumnType("TEXT");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("APIid");

                    b.HasIndex("NavAPIid");

                    b.ToTable("Nav");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.NavNav", b =>
                {
                    b.Property<string>("child_API_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("parent_API_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("childAPIid")
                        .HasColumnType("TEXT");

                    b.Property<string>("parentAPIid")
                        .HasColumnType("TEXT");

                    b.HasKey("child_API_Id", "parent_API_Id");

                    b.HasIndex("childAPIid");

                    b.HasIndex("parentAPIid");

                    b.ToTable("NavNav");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.Nav", b =>
                {
                    b.HasOne("BuildLogger_DB_Context.Nav", null)
                        .WithMany("navData")
                        .HasForeignKey("NavAPIid");
                });

            modelBuilder.Entity("BuildLogger_DB_Context.NavNav", b =>
                {
                    b.HasOne("BuildLogger_DB_Context.Nav", "child")
                        .WithMany()
                        .HasForeignKey("childAPIid");

                    b.HasOne("BuildLogger_DB_Context.Nav", "parent")
                        .WithMany()
                        .HasForeignKey("parentAPIid");
                });
#pragma warning restore 612, 618
        }
    }
}
